# Generated by Django 3.2.3 on 2022-05-02 16:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', '일반'), ('2', '계정'), ('3', '기타')], default='1', max_length=2, verbose_name='카테고리')),
                ('title', models.TextField(max_length=50, verbose_name='제목')),
                ('email_btn', models.BooleanField(default=False, verbose_name='이메일답변수신')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='이메일')),
                ('SMS_btn', models.BooleanField(default=False, verbose_name='문자메세지수신')),
                ('SMS', models.CharField(blank=True, max_length=50, null=True, verbose_name='문자메시지')),
                ('content', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('final_date', models.DateTimeField(auto_now=True, verbose_name='최종 수정일시')),
                ('in_final_modify', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_final_modify', to=settings.AUTH_USER_MODEL, verbose_name='최종 수정자')),
                ('in_writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_writer', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='질문')),
                ('category', models.CharField(choices=[('일반', '일반'), ('계정', '계정'), ('기타', '기타')], default='일반', max_length=10, verbose_name='카테고리')),
                ('answer', models.TextField(verbose_name='답변')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('final_date', models.DateTimeField(auto_now=True, verbose_name='최종 수정일시')),
                ('final_modify', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_modify', to=settings.AUTH_USER_MODEL, verbose_name='최종 수정자')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='답변 내용')),
                ('ans_date', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('ans_final_date', models.DateTimeField(auto_now=True, verbose_name='최종 수정일시')),
                ('ans_final_mod', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ans_final_mod', to=settings.AUTH_USER_MODEL, verbose_name='최종 수정자')),
                ('ans_writer', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='ans_writer', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.inquiry', verbose_name='참조 문의글')),
            ],
        ),
    ]
