# Generated by Django 3.2.3 on 2022-05-02 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='in_final_modify',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='in_writer',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='final_modify',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inq_modify', to=settings.AUTH_USER_MODEL, verbose_name='최종 수정자'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inq_writer', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='category',
            field=models.CharField(choices=[('1', '일반'), ('2', '계정'), ('3', '기타')], default='1', max_length=10, verbose_name='카테고리'),
        ),
    ]
