# Generated by Django 3.2.3 on 2022-04-19 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0002_faq_final_modify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=50, null=True, verbose_name='제목')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='이메일')),
                ('SMS', models.CharField(max_length=50, verbose_name='문자메시지')),
                ('content', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
            ],
        ),
        migrations.AlterField(
            model_name='faq',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='답변 내용')),
                ('ans_date', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('ans_final_date', models.DateTimeField(auto_now=True, verbose_name='최종 수정일시')),
                ('ans_final_mod', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ans_final_mod', to=settings.AUTH_USER_MODEL, verbose_name='최종 수정자')),
                ('ans_writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ans_writer', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.inquiry', verbose_name='참조 문의글')),
            ],
        ),
    ]
