# Generated by Django 3.2.3 on 2022-05-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20220503_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('1', '문의 등록'), ('2', '접수 완료'), ('3', '답변 완료')], default='1', max_length=2, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='category',
            field=models.CharField(choices=[('1', '일반'), ('2', '계정'), ('3', '기타')], default='1', max_length=2, verbose_name='카테고리'),
        ),
    ]
