# Generated by Django 3.2.3 on 2022-04-19 09:04

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0003_auto_20220419_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans_writer',
            field=models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ans_writer', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
    ]
