# Generated by Django 3.2.3 on 2022-05-01 13:08

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0004_alter_answer_ans_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='SMS_btn',
            field=models.BooleanField(default=False, verbose_name='문자메세지수신'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='email_btn',
            field=models.BooleanField(default=False, verbose_name='이메일답변수신'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_writer',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='ans_writer', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='SMS',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='문자메시지'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='title',
            field=models.TextField(max_length=50, verbose_name='제목'),
        ),
    ]
